### ISSUE TITLE
clap-sys vs. clap-rs

### ISSUE THREAD

**Issue by psychonaut** [glowcoil/clap-sys#15]
I know it would be hard to change the name because of the name of the upstream product and it's not really an issue but using the name Clap in Rust could be misleading because it's already taken by https://github.com/clap-rs/clap

Anyway, I really hope that this product will succeed because I big REAPER fan but I have constant problems with plugins available only on MS Windows or macOS.

**Comment by micahrj** [comment]
I'm not really worried about it, since it seems unlikely that `clap` will ever have a need for an associated `-sys` crate. If I had plans to publish more CLAP-related crates I would take care with the naming to avoid future conflicts (and I think this was part of @prokopyl's rationale for naming [clack](https://github.com/prokopyl/clack)).

I hope CLAP is successful as well!
